-- AGAI v238 — opérations atomiques et numérotation serveur multi-utilisateurs
-- Script réexécutable. Il ne supprime et ne transforme aucune donnée existante.
-- Compatible avec le mode public actuel (anon) et avec une future Supabase Auth.

create table if not exists public.agai_operation_log (
  id bigint generated by default as identity primary key,
  record_id text not null,
  caserne text not null,
  record_type text not null,
  action_type text not null,
  previous_status text,
  new_status text,
  previous_revision bigint not null default 0,
  new_revision bigint not null default 0,
  updated_by text,
  device_id text,
  app_version text,
  action_id text,
  created_at timestamptz not null default now()
);

create index if not exists agai_operation_log_record_created_idx
  on public.agai_operation_log(record_id, created_at desc);

create table if not exists public.agai_number_counters (
  scope text not null,
  period text not null,
  value bigint not null default 0,
  updated_at timestamptz not null default now(),
  primary key(scope,period)
);

revoke all on table public.agai_operation_log from public, anon, authenticated;
revoke all on table public.agai_number_counters from public, anon, authenticated;

create or replace function public.agai_allocate_number(p_scope text,p_period text,p_proposed bigint,p_existing_max bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare allocated bigint;
begin
  insert into public.agai_number_counters(scope,period,value,updated_at)
  values(p_scope,p_period,greatest(coalesce(p_existing_max,0),coalesce(p_proposed,1)-1)+1,now())
  on conflict(scope,period) do update set
    value=greatest(public.agai_number_counters.value,coalesce(p_existing_max,0),coalesce(p_proposed,1)-1)+1,
    updated_at=now()
  returning value into allocated;
  return allocated;
end;
$$;

create or replace function public.agai_record_vehicles(p_data jsonb)
returns text[]
language sql
immutable
set search_path = public
as $$
  select coalesce(array_agg(distinct vehicle) filter (where vehicle <> ''), array[]::text[])
  from unnest(array[
    coalesce(p_data->>'_engin1',''),
    coalesce(p_data->>'_engin2',''),
    coalesce(p_data->>'eng','')
  ]) as vehicle;
$$;

create or replace function public.agai_record_personnel(p_data jsonb)
returns text[]
language sql
immutable
set search_path = public
as $$
  with members(login) as (
    select coalesce(p_data->>'agr','')
    union all select coalesce(p_data->>'_agr2','')
    union all
      select coalesce(member->>'login','')
      from jsonb_array_elements(
        case when jsonb_typeof(p_data->'_equipage1')='array' then p_data->'_equipage1' else '[]'::jsonb end
      ) member
    union all
      select coalesce(member->>'login','')
      from jsonb_array_elements(
        case when jsonb_typeof(p_data->'_equipage2')='array' then p_data->'_equipage2' else '[]'::jsonb end
      ) member
  )
  select coalesce(array_agg(distinct login) filter (where login <> ''), array[]::text[]) from members;
$$;

create or replace function public.agai_atomic_upsert_record(
  p_id text,
  p_caserne text,
  p_type text,
  p_data jsonb,
  p_deleted boolean default false,
  p_updated_by text default '',
  p_expected_revision bigint default 0,
  p_expected_record_revision bigint default 0,
  p_device_id text default '',
  p_app_version text default '',
  p_action_id text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.records%rowtype;
  current_exists boolean := false;
  current_revision bigint := 0;
  current_record_revision bigint := 0;
  incoming_revision bigint := 0;
  current_status text := '';
  incoming_status text := coalesce(p_data->>'s','');
  wanted_vehicles text[] := public.agai_record_vehicles(p_data);
  wanted_personnel text[] := public.agai_record_personnel(p_data);
  conflicting_id text;
  numbered_stamp text;
  numbered_year text;
  numbered_month text;
  existing_max bigint;
  allocated_number bigint;
begin
  if p_type not in ('iv','pilp') then
    raise exception using errcode='22023', message='AGAI_TYPE_NOT_ATOMIC';
  end if;
  if p_id is null or p_caserne is null or p_data is null
     or p_id not like p_caserne||'__'||p_type||'__%' then
    raise exception using errcode='22023', message='AGAI_INVALID_RECORD';
  end if;

  -- Une seule transaction peut arbitrer cette fiche à la fois.
  perform pg_advisory_xact_lock(hashtext('agai-record:'||p_id));
  select * into current_row from public.records where id=p_id for update;
  current_exists := found;
  if current_exists then
    current_revision := coalesce(nullif(current_row.data->>'_statusRevision','')::bigint,0);
    current_record_revision := coalesce(nullif(current_row.data->>'_serverRevision','')::bigint,0);
    current_status := coalesce(current_row.data->>'s','');
  end if;
  incoming_revision := coalesce(nullif(p_data->>'_statusRevision','')::bigint,0);

  if current_revision <> coalesce(p_expected_revision,0) then
    raise exception using errcode='PT409',
      message='AGAI_REVISION_CONFLICT',
      detail='expected='||coalesce(p_expected_revision,0)||';current='||current_revision||';record='||p_id;
  end if;
  if current_record_revision <> coalesce(p_expected_record_revision,0) then
    raise exception using errcode='PT409',
      message='AGAI_RECORD_REVISION_CONFLICT',
      detail='expected='||coalesce(p_expected_record_revision,0)||';current='||current_record_revision||';record='||p_id;
  end if;
  if incoming_revision < current_revision then
    raise exception using errcode='PT409', message='AGAI_STALE_STATUS_REVISION';
  end if;
  if current_exists and current_status is distinct from incoming_status and incoming_revision <= current_revision then
    raise exception using errcode='PT409', message='AGAI_STATUS_REVISION_REQUIRED';
  end if;

  if incoming_status='en-cours' and not p_deleted then
    -- Verrou global : deux casernes ne peuvent pas engager le même agent au même instant.
    perform pg_advisory_xact_lock(hashtext('agai-active-engagements'));

    if cardinality(wanted_vehicles)>0 then
      select r.id into conflicting_id
      from public.records r
      where r.id<>p_id and not r.deleted and r.type in ('iv','pilp')
        and r.caserne=p_caserne and r.data->>'s'='en-cours'
        and public.agai_record_vehicles(r.data) && wanted_vehicles
      limit 1;
      if conflicting_id is not null then
        raise exception using errcode='23505', message='AGAI_VEHICLE_ALREADY_ENGAGED', detail=conflicting_id;
      end if;
    end if;

    conflicting_id := null;
    if cardinality(wanted_personnel)>0 then
      select r.id into conflicting_id
      from public.records r
      where r.id<>p_id and not r.deleted and r.type in ('iv','pilp')
        and r.data->>'s'='en-cours'
        and public.agai_record_personnel(r.data) && wanted_personnel
      limit 1;
      if conflicting_id is not null then
        raise exception using errcode='23505', message='AGAI_PERSON_ALREADY_ENGAGED', detail=conflicting_id;
      end if;
    end if;

    -- Les numéros sont contrôlés lors du premier passage En cours.
    if not current_exists or current_status<>'en-cours' then
      perform pg_advisory_xact_lock(hashtext('agai-numbering'));
      numbered_stamp := regexp_replace(coalesce(p_data->>'_numberedAtStart',p_data->>'h',''),'[^0-9]','','g');
      numbered_year := substring(numbered_stamp from 1 for 4);
      numbered_month := substring(numbered_stamp from 1 for 6);

      if coalesce(p_data->>'_isRenfort','false')<>'true' and coalesce(p_data->>'_numCaserne','')<>'' then
        select coalesce(max((r.data->>'_numCaserne')::bigint),0) into existing_max from public.records r
        where r.id<>p_id and not r.deleted and r.type in ('iv','pilp') and r.caserne=p_caserne
          and (r.data->>'_numCaserne')~'^[0-9]+$'
          and substring(regexp_replace(coalesce(r.data->>'_numberedAtStart',r.data->>'h',''),'[^0-9]','','g') from 1 for 4)=numbered_year;
        allocated_number:=public.agai_allocate_number('ut:'||p_caserne,numbered_year,(p_data->>'_numCaserne')::bigint,existing_max);
        p_data:=jsonb_set(p_data,'{_numCaserne}',to_jsonb(allocated_number),true);
      end if;

      if coalesce(p_data->>'_isRenfort','false')<>'true' and coalesce(p_data->>'_numGlobal','')<>'' then
        select coalesce(max((r.data->>'_numGlobal')::bigint),0) into existing_max from public.records r
        where r.id<>p_id and not r.deleted and r.type in ('iv','pilp')
          and (r.data->>'_numGlobal')~'^[0-9]+$'
          and substring(regexp_replace(coalesce(r.data->>'_numberedAtStart',r.data->>'h',''),'[^0-9]','','g') from 1 for 4)=numbered_year;
        allocated_number:=public.agai_allocate_number('global',numbered_year,(p_data->>'_numGlobal')::bigint,existing_max);
        p_data:=jsonb_set(p_data,'{_numGlobal}',to_jsonb(allocated_number),true);
      end if;

      if coalesce(p_data->>'_isRenfort','false')<>'true' and coalesce(p_data->>'_numMois','')<>'' then
        select coalesce(max((r.data->>'_numMois')::bigint),0) into existing_max from public.records r
        where r.id<>p_id and not r.deleted and r.type in ('iv','pilp') and r.caserne=p_caserne
          and (r.data->>'_numMois')~'^[0-9]+$'
          and substring(regexp_replace(coalesce(r.data->>'_numberedAtStart',r.data->>'h',''),'[^0-9]','','g') from 1 for 6)=numbered_month;
        allocated_number:=public.agai_allocate_number('month:'||p_caserne,numbered_month,(p_data->>'_numMois')::bigint,existing_max);
        p_data:=jsonb_set(p_data,'{_numMois}',to_jsonb(allocated_number),true);
      end if;
    end if;
  end if;

  p_data := jsonb_set(p_data,'{_serverRevision}',to_jsonb(current_record_revision+1),true);

  insert into public.records(id,caserne,type,data,deleted,updated_by,updated_at)
  values(p_id,p_caserne,p_type,p_data,coalesce(p_deleted,false),coalesce(p_updated_by,''),now())
  on conflict(id) do update set
    caserne=excluded.caserne,type=excluded.type,data=excluded.data,deleted=excluded.deleted,
    updated_by=excluded.updated_by,updated_at=now();

  insert into public.agai_operation_log(
    record_id,caserne,record_type,action_type,previous_status,new_status,
    previous_revision,new_revision,updated_by,device_id,app_version,action_id
  ) values (
    p_id,p_caserne,p_type,
    case when current_status is distinct from incoming_status then 'status-transition' else 'update' end,
    nullif(current_status,''),nullif(incoming_status,''),current_revision,incoming_revision,
    p_updated_by,p_device_id,p_app_version,p_action_id
  );

  return jsonb_build_object('ok',true,'id',p_id,'revision',incoming_revision,'recordRevision',current_record_revision+1,'status',incoming_status,'data',p_data);
end;
$$;

create or replace function public.agai_atomic_health()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  duplicate_vehicles bigint;
  duplicate_personnel bigint;
  duplicate_numbers bigint;
begin
  select count(*) into duplicate_vehicles from (
    select r.caserne,vehicle
    from public.records r cross join lateral unnest(public.agai_record_vehicles(r.data)) vehicle
    where not r.deleted and r.type in ('iv','pilp') and r.data->>'s'='en-cours'
    group by r.caserne,vehicle having count(*)>1
  ) duplicates;
  select count(*) into duplicate_personnel from (
    select member
    from public.records r cross join lateral unnest(public.agai_record_personnel(r.data)) member
    where not r.deleted and r.type in ('iv','pilp') and r.data->>'s'='en-cours'
    group by member having count(*)>1
  ) duplicates;
  select count(*) into duplicate_numbers from (
    select r.caserne,
      substring(regexp_replace(coalesce(r.data->>'_numberedAtStart',r.data->>'h',''),'[^0-9]','','g') from 1 for 4) period,
      r.data->>'_numCaserne' number
    from public.records r
    where not r.deleted and r.type in ('iv','pilp') and coalesce(r.data->>'_numCaserne','')<>''
    group by r.caserne,period,number having count(*)>1
  ) duplicates;
  return jsonb_build_object(
    'ok',true,
    'version','v238',
    'serverTime',now(),
    'journalEntries',(select count(*) from public.agai_operation_log),
    'duplicateVehicles',duplicate_vehicles,
    'duplicatePersonnel',duplicate_personnel,
    'duplicateNumbers',duplicate_numbers,
    'counterScopes',(select count(*) from public.agai_number_counters)
  );
end;
$$;

revoke all on function public.agai_record_vehicles(jsonb) from public, anon, authenticated;
revoke all on function public.agai_record_personnel(jsonb) from public, anon, authenticated;
revoke all on function public.agai_allocate_number(text,text,bigint,bigint) from public, anon, authenticated;
revoke all on function public.agai_atomic_upsert_record(text,text,text,jsonb,boolean,text,bigint,bigint,text,text,text) from public;
revoke all on function public.agai_atomic_health() from public;

-- Compatibilité avec l’application actuelle. Après migration vers Supabase Auth,
-- le droit anon pourra être retiré sans modifier l’application.
grant execute on function public.agai_atomic_upsert_record(text,text,text,jsonb,boolean,text,bigint,bigint,text,text,text) to anon, authenticated;
grant execute on function public.agai_atomic_health() to anon, authenticated;
