const fs=require('fs');
const vm=require('vm');
const path=require('path');

const root=__dirname;
const htmlPath=path.join(root,'AGAI-securise.html');
const sqlPath=path.join(root,'supabase-security.sql');
const html=fs.readFileSync(htmlPath,'utf8');
const sql=fs.readFileSync(sqlPath,'utf8');
const failures=[];

function check(condition,message){
  if(!condition)failures.push(message);
}

const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
check(scripts.length===1,'Le script principal est introuvable ou dupliqué.');
scripts.forEach((script,index)=>{
  try{new vm.Script(script,{filename:'AGAI-inline-'+index+'.js'});}
  catch(error){failures.push('Erreur JavaScript : '+error.message);}
});

[
  /xkeysib-/i,
  /\$2a\$10\$/,
  /superadmin2025/i,
  /chefcorps2025/i,
  /admin123/i,
  /api\.brevo\.com/i
].forEach(pattern=>check(!pattern.test(html),'Secret ou ancien identifiant détecté : '+pattern));

check(/const GLOBAL_ACCOUNTS=\[\];/.test(html),'Des comptes privilégiés sont encore initialisés dans le code.');
check(/const defaultUsers=\[\];/.test(html),'Un administrateur par défaut est encore créé.');
check(/function passwordPolicyError\(/.test(html),'La politique de mot de passe est absente.');
check(/function normalizeAllAccountMetadata\(/.test(html),'L’association comptes, casernes et rôles est absente.');
check(/function isResponsableFormation\(user\)/.test(html)&&/function canAccessFraisAdministratifs\(\)/.test(html),'Le profil Responsable formation ou son accès aux frais administratifs est absent.');
check(/function setResponsableFormation\(caserneId,login\)/.test(html)&&/if\(!isSuperAdmin\(\)\)/.test(html)&&/selected\.caserneId=caserneId/.test(html),'Le responsable formation n’est pas défini exclusivement par le superadmin et rattaché à sa caserne.');
check(/function actTypesForCurrentUser\(\)/.test(html)&&/activityIsFraisAdministratifs\(a\)&&!canAccessFraisAdministratifs\(\)/.test(html),'Les frais administratifs ne sont pas correctement masqués aux profils non autorisés.');
check(/caserneId:CURRENT_CASERNE_ID,appRole:'agent'/.test(html),'Les nouveaux agents ne reçoivent pas leur périmètre d’accès.');
check(/function getCurrentAccessScope\(/.test(html),'Le périmètre du compte connecté est indisponible.');
check(/function agaiCheckNumberingConflicts\(/.test(html),'Le contrôle des doublons de numérotation est absent.');
check(/safe-area-inset-bottom/.test(html),'La gestion des zones sûres iPhone est absente.');
check(/100dvh/.test(html),'La hauteur dynamique des écrans mobiles est absente.');
check(/function syncViewportMetrics\(/.test(html),'La correction du viewport Safari est absente.');
check(/@media\(hover:hover\) and \(pointer:fine\)/.test(html),'Le rétablissement de la molette sur ordinateur est absent.');
check(/body\{overflow-y:visible;overscroll-behavior-y:auto;\}/.test(html),'Le défilement vertical ordinateur n’est pas explicitement autorisé.');
check(/@media\(orientation:landscape\) and \(max-height:500px\)/.test(html),'Le mode paysage compact est absent.');
check(/@media\(orientation:landscape\) and \(max-width:1400px\)/.test(html),'Le menu paysage compact est absent.');
check(/const APP_VERSION='20260802-astreinte-tel-desktop-107'/.test(html),'La version applicative attendue est absente.');
check(/const SESSION_STORAGE_KEY = 'agai_session_v2'/.test(html)&&/function _restoreSessionAfterLoad\(\)/.test(html)&&/function _prepareSessionForPageExit\(\)/.test(html),'La restauration de session après un rechargement est absente.');
check(/backgroundLimit>0&&backgroundAt&&now-backgroundAt>=backgroundLimit/.test(html)&&/localStorage\.removeItem\(SESSION_STORAGE_KEY\)/.test(html),'Le délai de déconnexion en arrière-plan n’est pas respecté par la session restaurée.');
check(/const COMPTE_RENDU_DRAFT_PREFIX='agai_cr_draft_'/.test(html)&&/function writeCompteRenduDraft\(ivId,text,updatedAt\)/.test(html)&&/oninput="onCompteRenduDraftInput\(this\)"/.test(html),'La sauvegarde automatique du brouillon de compte rendu est absente.');
check(/iv\._crLocalSavedAt\s*=\s*savedAt/.test(html)&&/if\(typeof _jbEditLock!=='undefined'\)_jbEditLock=Date\.now\(\);\s*saveData\(true\)/.test(html),'L’enregistrement du compte rendu n’est pas protégé contre la synchronisation.');
check(/activeReportSnapshot&&Date\.now\(\)-_jbEditLock<15000/.test(html),'Le compte rendu actif n’est pas protégé pendant une réception distante.');
check(/function interventionTerminationSortKey\(iv\)/.test(html)&&/entry\.s==='terminee'/.test(html)&&/interventionTerminationSortKey\(a\)\.localeCompare\(interventionTerminationSortKey\(b\)\)/.test(html),'Le tri stable des interventions terminées est absent.');
check(/\.mov\.cr-modal-overlay\{/.test(html)&&/--visual-offset-top/.test(html)&&/function keepCompteRenduFieldVisible\(\)/.test(html)&&/reportOverlay\.classList\.add\('cr-modal-overlay'\)/.test(html),'Le compte rendu n’est pas stabilisé au-dessus du clavier mobile.');
check(/function interventionTeammateEditorHTML\(iv\)/.test(html)&&/function saveInterventionTeammate\(ivId\)/.test(html)&&/pushTL\(iv,'modif-equipier'/.test(html),'La correction tracée de l’équipier dans le compte rendu est absente.');
check(/isInterventionReportChef\(iv,CU\.l\)\|\|hasAdministrativeAccount\(\)/.test(html)&&/\.cr-teammate-grid\{grid-template-columns:minmax\(0,1fr\);\}/.test(html),'Les droits ou l’affichage mobile de la correction d’équipier sont absents.');
check(/function _frelonHasDestruction\(iv\)/.test(html)&&/id="frel-destruction"/.test(html)&&/id="frelon-detail-wrap"/.test(html)&&/if\(!destruction\)\{[\s\S]{0,100}iv\._frelonData=null/.test(html),'Le formulaire de destruction de nid n’est pas correctement conditionné.');
check(/function interventionCrewSignature\(iv,equipage1,equipage2\)/.test(html)&&/function isFollowingInterventionInSeries\(iv\)/.test(html)&&/iv\._startLockedByChain=true/.test(html)&&/if\(isFollowingInterventionInSeries\(iv\)\)return false/.test(html),'Le verrouillage horaire des interventions enchaînées avec le même équipage est absent.');
check(/function editFiltCommune\(q\)/.test(html)&&/function editSelectCommune\(commune,event\)/.test(html)&&/function editAddrAutocomplete\(q\)/.test(html)&&/nominatim\.openstreetmap\.org\/search\?q=\$\{query\}/.test(html),'La vérification des communes et des adresses est absente de la correction.');
check(/const commune=String\(editCommuneSelected\|\|''\)\.trim\(\)/.test(html)&&/iv\.com=commune/.test(html)&&/notes\.push\('Commune : '/.test(html),'La commune validée ou sa traçabilité est absente.');
check(/Frais administratif chef de corps/.test(html)&&/Frais administratif chef unit\\u00e9 territoriale/.test(html)&&/Frais administratif responsable formation/.test(html),'Les nouveaux libellés des frais administratifs sont absents.');
check(/function normalizeAdminExpenseType\(label\)/.test(html)&&/normalizedActLabels=new Set\(\)/.test(html),'La migration et la déduplication des anciens frais administratifs sont absentes.');
check(/function activityVisibleInHistory\(a\)/.test(html)&&/actGetData\(\)\.filter\(activityVisibleInHistory\)/.test(html),'Les frais administratifs ne sont pas filtrés dans l’historique des activités.');
check(/if\(activityIsFraisAdministratifs\(a\)&&!canAccessFraisAdministratifs\(\)\)return false/.test(html)&&/a\.participants\.includes\(CU\.l\)/.test(html),'La confidentialité ou la participation aux frais administratifs n’est pas contrôlée.');
check(/id="admin-monthly-export-btn"/.test(html)&&/openAdminMonthlyExport\(\)/.test(html),'Le bouton d’export mensuel administrateur est absent.');
check(/id="admin-export-month"/.test(html)&&/id="admin-export-year"/.test(html)&&/function adminMonthlyPeriod\(\)/.test(html),'Le choix du mois et de l’année pour l’export est absent.');
check(/un seul onglet « Registre »/.test(html)&&/book_append_sheet\(wb,adminExportSheet\(XLSX,ivHeaders,registreRows,ivWidths\),'Registre'\)/.test(html)&&/Présent '\+\(i\+1\)/.test(html),'L’onglet Registre unique ou les 31 colonnes de participants sont absents.');
check(/const registreRows=ivRows\.concat\(actRows,formRows,astrTelRows\)/.test(html),'Les interventions, activités, formations et astreintes téléphoniques ne sont pas réunies dans le même onglet.');
check(/Numéro CABBALR/.test(html)&&/Compte rendu de mission/.test(html)&&/Autres à préciser/.test(html)&&/Rapport établi/.test(html),'Le registre des interventions ne reprend pas le modèle fourni.');
check(/adminExportInterventionPresents/.test(html)&&/adminExportPad31/.test(html)&&/cellStyles:true/.test(html),'L’export mensuel ne conserve pas correctement les participants ou la présentation.');
check(/return u\?\[u\.nom\|\|'',u\.prenom\|\|''\]\.filter\(Boolean\)\.join\(' '\):login/.test(html),'Les agents exportés ne sont pas limités au nom et au prénom.');
check(/function adminExportPeople\(logins\)\{[\s\S]{0,180}adminExportUser\(login\)/.test(html)&&/out\.push\(adminExportUser\(login\)\)/.test(html),'Les fonctions des agents apparaissent encore dans les colonnes de participants.');
check(/function adminExportReportType\(iv\)/.test(html)&&/reportTypeCode\('renf'\)/.test(html)&&/reportTypeCode\('sdis'\)/.test(html)&&/reportTypeCode\('inter'\)/.test(html),'Les types de rapports INTER, SDIS et RENF sont absents.');
check(/function adminExportActivityReportType\(a\)/.test(html)&&/reportTypeCode\('fa'\)/.test(html)&&/reportTypeCode\('depl'\)/.test(html)&&/reportTypeCode\('ac'\)/.test(html)&&/reportTypeCode\('for'\)/.test(html)&&/reportTypeCode\('form'\)/.test(html),'Les types de rapports DEPL, FA, AC, FOR et FORM sont absents.');
check(/function adminExportInterventionRates\(iv\)/.test(html)&&/hour<7\|\|hour>=22/.test(html)&&/currentDate\.getDay\(\)===0\|\|getJoursFeries/.test(html),'Le calcul automatique des taux 100 %, 150 % et 200 % est absent.');
check(/function adminExportInterventionStartDate\(iv\)/.test(html)&&/entry&&entry\.s==='en-cours'/.test(html)&&/adminExportInterventionStartDate\(iv\)\.startsWith\(period\.prefixCompact\)/.test(html)&&/adminExportDateCompact\(adminExportInterventionStartDate\(iv\)\)/.test(html),'La date rÃ©elle de dÃ©but issue de lâ€™historique des interventions nâ€™est pas utilisÃ©e dans lâ€™export.');
check(/function adminExportExcelDurationValue\(value\)/.test(html)&&/header==='Heures'\|\|header==='Heures_2'/.test(html)&&/cell\.z='\[h\]:mm'/.test(html),'Les colonnes Heures de lâ€™export ne sont pas converties en durÃ©es Excel additionnables.');
check(/function activityVisibleInHistory\(a\)/.test(html)&&/function formationVisibleInHistory\(f,includeFormateurs\)/.test(html)&&/fmpaGetData\(\)\.filter\(function\(f\)\{return formationVisibleInHistory\(f,true\);\}\)/.test(html),'Le filtrage personnel des historiques dâ€™activitÃ©s et de formations est absent.');
check(/RC_PENDING_DIRTY_KEY = 'agai_rc_pending_dirty'/.test(html)&&/function _rcTrackChangedRecords\(previousData,nextData\)/.test(html)&&/function _rcScheduleRetry\(delay\)/.test(html)&&/if\(_rcPendingDirty\.size\)\{[\s\S]{0,80}_jbSetStatus\('pending'\)/.test(html),'La file persistante de synchronisation des actions critiques est absente.');
check(/join_ref:joinRef/.test(html)&&/m\.event==='phx_reply'&&m\.ref===ws\._agaiJoinRef/.test(html),'L’abonnement Supabase Realtime n’est pas confirmé selon le protocole du canal.');
check(/function _rcApplyRealtimeInterventionRecord\(record\)/.test(html)&&/record\.type==='iv'\?'ivs'/.test(html)&&/_rcRenderRealtimeViews\(\)/.test(html),'Les changements de statut reçus ne sont pas appliqués immédiatement à la liste des interventions.');
check(/function _rcRequestRealtimePull\(delay\)/.test(html)&&/_rcRealtimePullPending=true/.test(html)&&/if\(!applied\)_rcRequestRealtimePull\(0\)/.test(html),'Les événements temps réel différés ne sont pas rattrapés automatiquement.');
check(/document\.addEventListener\('visibilitychange'/.test(html)&&/_rcRequestRealtimePull\(0\)/.test(html),'La synchronisation n’est pas relancée au retour sur l’application mobile.');
check(/const isSdis=adminExportReportType\(iv\)==='SDIS'/.test(html)&&/isSdis\?\(iv\._hAcquis\|\|adminExportTimeCompact\(iv\.h\)\):''/.test(html)&&/isSdis\?\(iv\._hSll\|\|''\):''/.test(html)&&/isSdis\?rapportAuteur:''/.test(html),'Les colonnes propres au rapport SDIS ne sont pas correctement limitées aux interventions SDIS.');
check(/function astrTelTotalJour\(y,m,day,excludeLogin\)/.test(html)&&/24-autres/.test(html)&&/Le total de la journée ne peut pas dépasser 24:00/.test(html),'Le plafond journalier global de 24 h pour l’astreinte téléphonique est absent.');
check(/const isAdminAccount=hasAdministrativeAccount\(\)/.test(html)&&/equipesBtn\.style\.display=isAdminAccount/.test(html),'Le sous-menu Équipes n’est pas visible directement pour les comptes administrateurs.');
check(/function isChefOuAdjoint\(\)[\s\S]{0,180}hasAdministrativeAccount\(\)/.test(html)&&/btnTel\.style\.display=isChefOuAdjoint\(\)/.test(html)&&/sub==='tel'&&!isChefOuAdjoint\(\)/.test(html),'La saisie des astreintes téléphoniques exige encore l’activation temporaire du mode administrateur.');
check(/function sortEquipes\(list\)[\s\S]{0,300}localeCompare[\s\S]{0,100}numeric:true/.test(html)&&/list\.innerHTML=sortEquipes\(EQUIPES\)\.map/.test(html),'Les équipes d’astreinte ne sont pas classées dans leur ordre numérique naturel.');
check(/function dispoDayLabel\(wk,dayIdx,full\)/.test(html)&&/dispoDayLabel\(wk,d,false\)/.test(html)&&/dispoDayLabel\(wk,d,true\)/.test(html)&&/const _lw=78/.test(html),'Les dates ne sont pas affichées à côté des jours dans les disponibilités.');
check(/astrTelData: JSON\.parse\(JSON\.stringify\(d\.astrTelData\|\|\{\}\)\)/.test(html)&&/out\.astrTelData=c\.astrTelData\|\|\{\}/.test(html),'L’astreinte téléphonique n’est pas conservée dans la synchronisation par enregistrements.');
check(/function astrTelParseHeures\(value\)/.test(html)&&/input type="text" inputmode="numeric" pattern="\[0-9:\]\*"/.test(html)&&/function astrTelCommitInput\(el\)/.test(html),'La saisie HH:MM directe et fluide des heures d’astreinte téléphonique est absente.');
check(/class="astrtel-agent-row"/.test(html)&&/function astrTelHighlightRow\(el\)/.test(html)&&/onfocus="astrTelHighlightRow\(this\);this\.select\(\);"/.test(html),'Le surlignage de la ligne active de l’astreinte téléphonique est absent.');
check(/const joursFeries=getJoursFeries\(y\)/.test(html)&&/isFerie\?'#F3E8FF':isWE\?'#fdf0f0'/.test(html)&&/>Jour férié<\/span>/.test(html),'La couleur distincte des jours fériés dans l’astreinte téléphonique est absente.');
check(!/astrtel-agent-row\.is-active>div\{/.test(html),'Le surlignage de ligne modifie encore la couleur des cellules du week-end.');
check(/\.astrtel-header-row\{\s*position:sticky/.test(html)&&/\.astrtel-sticky-agent\{left:0;\}/.test(html)&&/\.astrtel-sticky-total\{left:var\(--astrtel-agent-w,160px\)/.test(html),'Les dates, noms et totaux de l’astreinte téléphonique ne restent pas fixes.');
check(/max-height:max\(280px,65dvh\)/.test(html)&&/const agentW=mobileGrid\?118:160/.test(html)&&/const colW=mobileGrid\?48:36/.test(html)&&/const totalW=mobileGrid\?54:50/.test(html),'Le tableau d’astreinte téléphonique n’est pas adapté au défilement sur smartphone.');
check(/\.astrtel-agent-row input\{\s*min-height:44px;\s*font-size:16px!important/.test(html)&&/align-self:stretch/.test(html)&&/transform:translateZ\(0\)/.test(html),'Le zoom automatique ou le chevauchement des colonnes fixes sur smartphone n’est pas corrigé.');
check(/rates\.taux1,rates\.heures1,rates\.taux2,rates\.heures2/.test(html),'Le découpage entre Taux et Taux_2 n’est pas exporté.');
check((html.match(/if\(endMin<startMin\)endMin\+=1440/g)||[]).length>=3&&!/if\(endMin<=startMin\)endMin\+=1440/.test(html),'Une heure de début identique à l’heure de fin est encore comptée comme 24 heures.');
check(/if\(endMin===startMin\)\{[\s\S]{0,250}taux1:tauxZero\+'%',heures1:'00:00'/.test(html),'Le taux n’est pas conservé pour une intervention de durée nulle.');
check(/astrTel:5/.test(html)&&/id="ref-rate-\$\{r\.id\}"/.test(html)&&/id:'astrTel'/.test(html),'Le taux configurable de l’astreinte téléphonique est absent.');
check(/interJour:100,interDimFerie:150,interNuit:200/.test(html),'Les taux par défaut des interventions sont absents.');
check(/Interventions — journée \(07h–22h\)','interJour'/.test(html)&&/dimanche et jour férié \(07h–22h\)','interDimFerie'/.test(html)&&/Interventions — nuit \(22h–07h\)','interNuit'/.test(html),'Les trois taux d’intervention ne sont pas modifiables dans le menu superadmin.');
check(/function saveReportRatesFromRef\(\)/.test(html)&&/next\.exportAdmins=document\.getElementById\('ref-export-admins'\)/.test(html)&&/saveStatsTaux\(next\)/.test(html),'Tous les taux ou l’autorisation d’export ne sont pas enregistrés par le superadmin.');
check(/function getInterventionTauxConfigFor\(currentDate,hour,reportType\)/.test(html)&&/prefix=reportType==='SDIS'\?'sdis':reportType==='RENF'\?'renf':'inter'/.test(html)&&/t\[prefix\+'Nuit'\]/.test(html)&&/t\[prefix\+'DimFerie'\]/.test(html)&&/t\[prefix\+'Jour'\]/.test(html),'Les calculs n’utilisent pas les taux configurables par type d’intervention.');
check(/5:reportType,6:rate/.test(html)&&/adminExportFormationRegisterRow\(f,'Formation',reportTypeCode\('for'\),exportRates\.formStag\)/.test(html)&&/adminExportFormationRegisterRow\(f,'Formateur',reportTypeCode\('form'\),exportRates\.formRate\)/.test(html),'Les taux ou types des activités et formations ne sont pas exportés.');
check(/exportAdmins:false/.test(html)&&/function canUseMonthlyExport\(\)/.test(html)&&/isSuperAdmin\(\)\|\|\(hasRight\('Administration'\)&&getStatsTaux\(\)\.exportAdmins===true\)/.test(html),'L’export n’est pas réservé au superadmin par défaut.');
check(/id="export-admins-visible"/.test(html)&&/Autoriser l’export mensuel aux administrateurs/.test(html),'Le superadmin ne peut pas autoriser ou masquer l’export pour les admins.');
check(/Manoeuvre mensuel',reportTypeCode\('ac'\),exportRates\.actSvc/.test(html)&&/Formateur',reportTypeCode\('form'\),exportRates\.formRate/.test(html),'Les taux et types FMPA ne sont pas séparés entre stagiaires et formateurs.');
check(/function adminExportAstrTelRegisterRow/.test(html)&&/5:reportTypeCode\('ast'\),6:exportRates\.astrTel\+'%'/.test(html)&&/7:astrTelFormatHeures\(a\.heures\)/.test(html),'Les astreintes téléphoniques mensuelles ne sont pas exportées avec leur taux et leur durée.');
check(/function adminExportActivityRegisterRow[\s\S]{0,600}return adminExportRegisterRow\(\{\s*4:/.test(html)&&/function adminExportFmpaRegisterRows[\s\S]{0,800}4:adminExportDateIso\(f\.date\)/.test(html)&&/function adminExportFormationRegisterRow[\s\S]{0,500}4:adminExportDateIso\(f\.ddebut\)/.test(html),'Les numéros et champs de rapport interdits ne sont pas laissés vides pour les activités et formations.');
check(/Heures pondérées d\\'activités de service/.test(html)&&/Heures pondérées de formations/.test(html)&&/Taux pondéré/.test(html),'Les taux configurés ne sont pas appliqués aux statistiques.');
check(/function getMembresExport\(p\)/.test(html)&&/const noms=list\.map\(function\(p,i\)/.test(html)&&/join\('\\n\\n'\)/.test(html),'L’export récapitulatif perd encore les piquets multiples.');
check(/Donn\\u00e9es compl\\u00e8tes/.test(html)&&/une ligne par agent affect/.test(html)&&/D\\u00e9but agent/.test(html)&&/Fin agent/.test(html),'L’onglet exhaustif des piquets est absent de l’export.');
check(/const isToday=getDS\(jourDate\)===getDS\(N\(\)\)/.test(html)&&!/const isToday=di===todayIdx/.test(html),'Le repère Aujourd’hui des piquets ne compare pas la date complète.');
check(/Matin 08:00&ndash;12:00/.test(html)&&/Apr&egrave;s-midi 12:00&ndash;18:00/.test(html)&&/Soir 18:00&ndash;00:00/.test(html)&&/Nuit 00:00&ndash;08:00/.test(html),'La légende des quatre périodes de piquet est absente.');
check(/const tranches=\{m:\[\],a:\[\],s:\[\],n:\[\]\}/.test(html)&&/tranches\.a/.test(html)&&/tranches\.s/.test(html),'La colonne Soir des piquets est absente.');
check(/if\(d<8\*60\)return 'nuit';[\s\S]{0,120}if\(d<12\*60\)return 'matin';[\s\S]{0,120}if\(d<18\*60\)return 'am';[\s\S]{0,80}return 'soir'/.test(html),'Les horaires des périodes de piquet ne sont pas correctement répartis.');
check(/\['Engin','Matin','Cr\\u00e9neau','Apr\\u00e8s-midi','Cr\\u00e9neau','Soir','Cr\\u00e9neau','Nuit','Cr\\u00e9neau'\]/.test(html)&&/trancheData\(pJour,'soir'\)/.test(html),'La période Soir est absente de l’export des piquets.');
check(!/Matin<br><small>08&ndash;12/.test(html)&&!/Soir<br><small>18&ndash;00/.test(html),'Les horaires apparaissent encore dans les titres des colonnes des piquets.');
check(/class="nature-option"[\s\S]*?onclick="sN\(/.test(html)&&/const doubleTap=/.test(html),'Le double appui tactile sur une nature est absent.');
check(/#e1\.appel-nature-step/.test(html)&&/function syncAppelNatureViewport\(/.test(html),'L’écran Nature pleine hauteur est absent.');
check(/html\.appel-nature-locked[\s\S]*?overflow:hidden!important/.test(html)&&/#nl\.appel-nature-list[\s\S]*?overflow-y:auto!important/.test(html),'Le défilement doit être limité à la liste des natures.');
check(/function addAppelPhone\(/.test(html)&&/data-appel-phone/.test(html)&&/tels\[0\]\|\|''/.test(html),'La gestion de plusieurs numéros de téléphone est absente.');
check(/id="req-dispo-state"/.test(html)&&/id="req-dispo-mode"/.test(html)&&/function getReqAvailability\(/.test(html),'La disponibilité horaire du requérant est absente.');
check(/data-req-dispo-day/.test(html)&&/function addReqAvailabilityDay\(/.test(html)&&/days:getReqAvailabilityDays|const days=getReqAvailabilityDays/.test(html),'La sélection d’un ou plusieurs jours de disponibilité est absente.');
check(/option value="indisponible"/.test(html)&&/state==='indisponible'/.test(html),'L’indisponibilité du requérant n’est pas prise en charge.');
check(/id="chk-erp"/.test(html)&&/_urgence:erp/.test(html)&&/URGENCE ERP/.test(html),'Le classement ERP en urgence est absent.');
check(/\.ivr\.urgence\{box-shadow:none;\}/.test(html)&&!/\.ivr\.urgence\{[^}]*border:2px solid #B91C1C/.test(html),'Le contour rouge des interventions ERP urgentes est encore présent.');
check(/\.nav \.nb\{[\s\S]{0,250}font-weight:500/.test(html)&&/\.nav \.nb\.active\{font-weight:600;\}/.test(html),'La graisse allégée du menu principal est absente.');
check(/\.subtab-btn\{font-size:15px;font-weight:500/.test(html)&&/\.subtab-btn\.active\{font-weight:600;\}/.test(html),'La graisse allégée des sous-menus est absente.');
check(/id="appel-animals"/.test(html)&&/function addAppelAnimal\(/.test(html)&&/_animauxAppel:animauxAppel/.test(html),'La saisie de plusieurs animaux pendant l’appel est absente.');
check(/function selectAppelAnimalOption\(/.test(html)&&/data-animal-field="type"/.test(html)&&/data-animal-field="situation"/.test(html),'La sélection visuelle du type et de la situation des animaux est absente.');
check(/function getPrisesEnChargeAnimal\(/.test(html)&&/function showPrisesEnChargeManager\(/.test(html)&&/iv\._prisesEnCharge=fiches/.test(html),'La gestion de plusieurs fiches animales est absente.');
check(/pecRecords\.forEach\(function\(record,index\)/.test(html)&&/_buildPriseEnChargeHTML\(ivId,index\)/.test(html)&&/pecPagesHtml\+=/.test(html),'Toutes les fiches animales ne sont pas jointes au compte rendu.');
check(/id="pec-telephone"/.test(html)&&/telephone:[\s\S]{0,120}pec-telephone/.test(html),'Le téléphone de la prise en charge animale est absent.');
check(/modal-scroll-locked/.test(html)&&/function syncModalBackgroundLock\(/.test(html)&&/MutationObserver\(syncModalBackgroundLock\)/.test(html),'Le verrouillage de l’arrière-plan des fiches est absent.');
check(/function deleteAllLoginHistory\(/.test(html)&&/function deleteSelectedLoginHistory\(/.test(html),'Les suppressions complète et sélective des connexions sont absentes.');
check(/class="login-history-check"/.test(html)&&/class="login-history-group-all"/.test(html),'La sélection des historiques de connexion est absente.');
check(/LOGIN_HISTORY_DELETED/.test(html)&&/_mergeLoginHistory\(localArr, remoteArr, deletedMap\)/.test(html),'La persistance des suppressions de connexion est absente.');
check(/hist-report-badge validated/.test(html)&&/Rapport validé/.test(html),'Le badge visible de validation du rapport est absent.');
check(/hist-report-badge printed/.test(html)&&/Rapport imprimé/.test(html),'Le badge visible d’impression du rapport est absent.');
check(/\.hm\.report-complete/.test(html),'La mise en évidence des rapports validés et imprimés est absente.');
check(/id="cr-save-status"/.test(html)&&/la fenêtre reste ouverte/.test(html),'La sauvegarde du rapport ne confirme pas le maintien de la fenêtre ouverte.');
check(!/else\{cM\(\);setTimeout\(function\(\)\{oM\(ivId\)/.test(html),'La sauvegarde simple ferme encore la fenêtre du rapport.');
check(/const _numeroOrdre=iv=>/.test(html)&&/const byNumber=_numeroOrdre\(b\)-_numeroOrdre\(a\)/.test(html),'Le départage des interventions à heure identique est absent.');
check(/const _jour=iv=>[\s\S]{0,800}entry\.s==='en-cours'/.test(html)&&/const h=_jour\(iv\),y=h\.slice/.test(html),'Le classement selon la date réelle de départ en intervention est absent.');
check(/async function _fetchRemoteVersion\(/.test(html),'La détection du manifeste de version est absente.');
check(/new URL\('version\.json',document\.baseURI\)/.test(html),'Le manifeste de mise à jour n’est pas interrogé.');
check(/id="ver-reload-button"/.test(html),'Le bouton d’actualisation de version est absent.');
check(/url\.searchParams\.set\('_refresh',Date\.now\(\)\)/.test(html),'Le rechargement forcé sans cache est absent.');
check(/input\.fi\[type="date"\],input\.fi\[type="time"\][\s\S]*?-webkit-appearance:none;appearance:none/.test(html),'La normalisation WebKit des dates et heures est absente.');
check(/min-height:48px!important;height:48px!important;max-height:48px!important/.test(html),'La hauteur fixe tactile des dates et heures est absente.');
check(/\.fi\{min-height:48px!important;\}/.test(html),'La hauteur uniforme des champs mobiles est absente.');
check(/::-webkit-date-and-time-value[\s\S]*?height:26px;line-height:26px/.test(html),'L’alignement interne des dates et heures sur smartphone est absent.');
check(/#act-form-panel \.fg-horaires,#fmpa-form-panel \.fg-horaires/.test(html),'La grille horaire mobile des activités et FMPA est absente.');
check(/#formstag-form-panel \.fg-horaires,#formform-form-panel \.fg-horaires/.test(html),'La grille horaire mobile des formations est absente.');
check(/@media\(orientation:portrait\) and \(pointer:coarse\) and \(max-width:600px\)/.test(html),'La disposition portrait des formulaires smartphone est absente.');
check(/@media\(hover:hover\) and \(pointer:fine\) and \(min-width:1024px\)/.test(html),'La typographie des menus ordinateur est absente.');
check(/\.nav \.nb \.nb-txt,[\s\S]*?font-size:15px/.test(html),'L’agrandissement des libellés du menu ordinateur est absent.');
check(/@media\(hover:hover\) and \(pointer:fine\) and \(min-width:1600px\)/.test(html),'La taille des menus sur grand écran est absente.');
check(/function dureeMinutesHHMM\(/.test(html)&&/function dureeValeurMinutes\(/.test(html),'Les fonctions de durée HH:MM sont absentes.');
check(/function dureeFormatHHMM\(/.test(html),'La compatibilité avec les anciennes durées est absente.');
check(/function actCalcDuree\(\)[\s\S]{0,700}el\.value=dureeMinutesHHMM\(mins\)/.test(html),'La durée HH:MM des activités est absente.');
check(/function fmpaCalcDuree\(\)[\s\S]{0,700}el\.value=dureeMinutesHHMM\(mins\)/.test(html),'La durée HH:MM des FMPA est absente.');
check(/function formMinsToStr\(m\)\{return dureeMinutesHHMM\(m\);\}/.test(html),'La durée HH:MM des formations est absente.');
check(/dureeValeurMinutes\(a\.duree\)\*tauxAct\/100/.test(html),'Les anciennes durées ne sont pas compatibles avec les statistiques pondérées.');
check(/const next=cur===true\?false:true/.test(html),'Le cycle vert/rouge des disponibilités est absent.');
check(/_dragTargetVal=cur===true\?false:true/.test(html),'Le glisser vert/rouge des disponibilités est absent.');
check(/function _finishDispoGesture\(cancelled\)[\s\S]{0,300}!_dispoGestureMoved/.test(html),'L’appui simple sur un créneau de disponibilité est absent.');
check(/const urgenceActiveA=!!a\._urgence&&a\.s!=='terminee'/.test(html),'Une intervention ERP terminée peut encore rester prioritaire.');
check(/if\(a\.s==='terminee'\)return interventionTerminationSortKey\(a\)\.localeCompare\(interventionTerminationSortKey\(b\)\)/.test(html),'Les interventions terminées ne sont pas conservées dans l’ordre chronologique.');
check(/function openModalAtTop\(focusId\)/.test(html)&&/openModalAtTop\('cancel-motif'\)/.test(html)&&/openModalAtTop\('compl-info-val'\)/.test(html),'Les zones d’annulation et de complément ne sont pas replacées en haut sur smartphone.');
check(/\.pec-form-scroll\{[\s\S]{0,500}overflow-x:hidden/.test(html)&&/\.pec-form-grid\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/.test(html),'Le formulaire de prise en charge animale n’est pas verrouillé à la largeur disponible.');
check(/\.pec-form-grid\{grid-template-columns:minmax\(0,1fr\)!important;\}/.test(html),'La fiche animale ne passe pas en une colonne sur smartphone.');
check(/\.mov\.pec-modal-overlay\{[\s\S]{0,500}height:var\(--app-height\)/.test(html)&&/\.mov\.pec-modal-overlay\.pec-form-active #mb\{overflow:hidden;\}/.test(html),'La fiche animale ne reste pas contenue dans le viewport mobile.');
check(/function prepareAnimalModal\(formActive\)/.test(html)&&/prepareAnimalModal\(true\);\s*openModalAtTop\(\);\s*registerMobileModalFields/.test(html),'Le mode mobile de la fiche animale nâ€™est pas activé à son ouverture.');
check(/function registerMobileModalFields\(root\)/.test(html)&&/field\.closest\('\.pec-form-scroll'\)/.test(html),'Les champs de la fiche animale ne restent pas visibles au-dessus du clavier.');
check(/classList\.remove\('cr-modal-overlay','pec-modal-overlay','pec-form-active'\)/.test(html),'Le mode plein écran de la fiche animale nâ€™est pas correctement nettoyé.');
check(/id="intervention-filter-row"/.test(html)&&/\.intervention-filter-row\{[\s\S]{0,250}grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/.test(html),'Le bandeau des interventions ne passe pas sur deux lignes en portrait smartphone.');
check(/\.intervention-filter-row \.fb\{[\s\S]{0,150}min-height:38px/.test(html),'Le bandeau des interventions reste trop haut sur smartphone.');
check(/id="pilp-filter-row"/.test(html)&&/lancerItinerairePilp\(\)/.test(html)&&/pilp-fb-mes-sel/.test(html)&&/pilp-fb-mes-resp/.test(html),'Le bandeau PILP n’est pas aligné sur celui des interventions.');
check(!/Interventions PILP<\/div>[\s\S]{0,180}pistolet insecticide longue portée/.test(html),'L’ancien bandeau descriptif PILP est encore présent.');
check(/IVS\.find\(v=>v\.id===id\)\|\|PILP_IVS\.find\(v=>v\.id===id\)/.test(html),'Les itinéraires ne prennent pas en charge les interventions PILP.');
check(/function canSeePILP\(\)\{return isTireurPILP\(\);\}/.test(html),'La visibilité PILP n’est pas strictement réservée aux tireurs PILP.');
check(/if\(sub==='pilp'&&!isTireurPILP\(\)\)/.test(html)&&/function rPilp\(\)\{[\s\S]{0,100}!isTireurPILP\(\)/.test(html),'L’accès au menu PILP n’est pas bloqué pour les non-tireurs.');
check(/const pilpStats=isTireurPILP\(\)\?PILP_IVS\.filter/.test(html)&&/const nbMois=[\s\S]{0,220}pilpStats\.filter/.test(html),'Les statistiques PILP de l’accueil ne respectent pas les droits ou la période mensuelle.');
check(/class="acc-agenda-grid"/.test(html)&&/function renderAgendaCard\(/.test(html),'Le résumé compact disponibilités et piquets est absent de l’accueil.');
check(/\.hist-num-ut,\.hist-num-m\{font-size:12px;font-weight:800/.test(html)&&/class="hist-num-ut"/.test(html)&&/class="hist-num-m"/.test(html),'Les numéros UT et M de l’historique ne sont pas agrandis.');
check(/class="astr-landscape-guard"/.test(html)&&/@media\(orientation:portrait\) and \(pointer:coarse\) and \(max-width:1024px\)/.test(html),'Le verrouillage paysage du menu Astreintes est absent.');
check(/#tab-astreintes\.active>:not\(\.astr-landscape-guard\)\{display:none!important;\}/.test(html),'Le contenu Astreintes reste accessible en mode portrait.');
check(!/else if\(cur===false\)\{delete DISPOS\[wk\]\[login\]\[key\]/.test(html),'Une cellule peut encore revenir individuellement au gris.');
check(!/reqApplyAllVal\(\\'null\\'\)/.test(html),'Une demande de modification peut encore remettre un créneau au gris.');
check(/function clearAllDispoFor\(/.test(html)&&/Tout effacer et remettre tous les créneaux en gris/.test(html),'La remise à zéro globale des disponibilités est absente.');
check(/setAllDispoFor\(wk,login,null,eqColor,true\)/.test(html),'La remise au gris n’est pas réservée à Tout effacer.');
check(/@media\(hover:none\) and \(pointer:coarse\)[\s\S]*?overflow-y:auto!important/.test(html),'Le défilement vertical tactile multi-navigateurs est absent.');
check(/\.dispo-cell\{[\s\S]*?touch-action:none!important/.test(html),'La surface tactile des disponibilités est absente.');
check(/if\(window\.PointerEvent\)/.test(html),'La gestion tactile moderne des disponibilités est absente.');
check(/addEventListener\('pointerdown'/.test(html)&&/addEventListener\('pointermove'/.test(html),'Le glissement Android/iPhone des disponibilités est incomplet.');
check(/Repli pour les anciens appareils/.test(html)&&/addEventListener\('touchstart'/.test(html),'Le repli tactile ancien navigateur est absent.');
check(/deleteActivite\('\$\{id\}'\)/.test(html)&&/deleteFmpa\('\$\{id\}'\)/.test(html),'Les suppressions superadmin ne sont pas proposées dans les détails.');
check(/await _rcMarkDeleted\(CURRENT_CASERNE_ID,'activite',\[id\]\)/.test(html),'La suppression synchronisée des activités est absente.');
check(/await _rcMarkDeleted\(CURRENT_CASERNE_ID,recType,\[id\]\)/.test(html),'La suppression synchronisée des formations est absente.');
check((html.match(/class="btn sm form-panel-close"/g)||[]).length===4,'Les boutons de fermeture des formulaires sont incomplets.');
check(/btn\.style\.display=willOpen\?'none':''/.test(html),'Le bouton extérieur des formulaires n’est pas masqué à l’ouverture.');
check(/const _blockInset=22/.test(html),'La compensation du padding de la grille des disponibilités est absente.');
check(/const _desktopFit=window\.matchMedia/.test(html),'L’ajustement sans défilement des disponibilités sur ordinateur est absent.');
check(/_desktopFit\?Math\.max\(1,_availableW\/slotsDay0\)/.test(html),'La répartition des créneaux sur toute la largeur ordinateur est absente.');
check(/dernier créneau 07h–08h/.test(html),'La correction du dernier créneau horaire est absente.');
check(/function _sendMailSecure\(/.test(html),'La passerelle mail sécurisée est absente.');
check(/function agaiExportBackup\(/.test(html)&&/function agaiImportBackup\(/.test(html),'La sauvegarde/restauration est incomplète.');
check(/enable row level security/i.test(sql),'RLS n’est pas activée dans le script Supabase.');
check(/agai_next_counter/i.test(sql),'Le compteur atomique Supabase est absent.');
check(/\.mov\.keyboard-aware-modal\{[\s\S]{0,260}height:var\(--app-height\)/.test(html)&&/function keepMobileModalFieldVisible\(\)/.test(html),'La fenÃªtre dâ€™information ne reste pas visible au-dessus du clavier mobile.');
check(/activateMobileModalField\('compl-info-val'\)/.test(html),'Le champ de complÃ©ment nâ€™active pas le suivi du clavier mobile.');
check(/Heure de d\\u00e9but : /.test(html)&&/Intervention encha\\u00een\\u00e9e avec le m\\u00eame \\u00e9quipage/.test(html),'Le texte du compte rendu mobile nâ€™utilise pas un encodage sÃ»r.');
check(/@media\(min-width:901px\) and \(pointer:fine\)\{[\s\S]{0,900}\.mov\.cr-modal-overlay \.mod\{[\s\S]{0,300}width:min\(920px,calc\(100vw - 64px\)\)[\s\S]{0,300}height:auto/.test(html),'Le compte rendu ne sâ€™ouvre pas dans une fenÃªtre centrÃ©e sur ordinateur.');
check(/background:rgba\(15,23,42,\.52\)/.test(html)&&/box-shadow:0 24px 70px rgba\(15,23,42,\.28\)/.test(html),'La distinction visuelle de la fenÃªtre de rapport sur ordinateur est absente.');
check(/function statsInterventionDateKey\(iv\)[\s\S]{0,500}adminExportInterventionStartDate\(iv\)/.test(html),'Les statistiques ne reposent pas sur la date rÃ©elle de dÃ©but dâ€™intervention.');
check(/function getStIvs\(\)[\s\S]{0,450}isInterventionComptabilisee\(iv\)&&statsInterventionInPeriod/.test(html),'Les statistiques principales ne sont pas limitÃ©es aux interventions comptabilisables.');
check(/function renderGlobalStats\(\)[\s\S]{0,500}const ivs=\(d\.ivs\|\|\[\]\)\.filter\(iv=>!iv\._isPilip&&isInterventionComptabilisee\(iv\)\)/.test(html)&&/const globalCasernes=OP_CASERNES\(\)[\s\S]{0,1400}const totD=globalCasernes\.reduce/.test(html),'Les lignes et le total des statistiques globales n utilisent pas le meme perimetre.');
check(/function fmpaMinsPour\(f\)[\s\S]{0,300}if\(d<0\)d\+=1440/.test(html),'Les FMPA traversant minuit ont une durÃ©e statistique incorrecte.');
check(/if\(dt\.getFullYear\(\)!==stAnnee\)return/.test(html)&&/if\(piquetDate\.getFullYear\(\)!==stAnnee\)return/.test(html),'Les disponibilitÃ©s ou piquets ne sont pas rattachÃ©s Ã  leur date civile rÃ©elle.');
check(/rateBadge\('INTER'/.test(html)&&/rateBadge\('SDIS'/.test(html)&&/rateBadge\('RENF'/.test(html),'Les taux configurables ne sont pas visibles dans les statistiques du personnel.');

check(/function interventionMainDriver\(iv\)/.test(html)&&/id="cr-conducteur"/.test(html)&&/id="cr-equipier"/.test(html)&&/traceRole\('Conducteur','conducteur'/.test(html),'La correction tracee du conducteur est absente du compte rendu.');
check(/function interventionMainReportCrew\(iv\)/.test(html)&&/interventionMainReportCrew\(iv\)\.forEach/.test(html),'Le conducteur et equipier ne sont pas repris ensemble dans le rapport.');

check(/function historyIsoWeekInfo\(dateKey\)/.test(html)&&/class="hist-week-block"/.test(html)&&/class="hist-day-block"/.test(html),'Le regroupement repliable de l historique par semaine et par jour est absent.');
check(/const HIST_GROUP_STATE=\{\}/.test(html)&&/function historyGroupOpen\(id,defaultOpen\)/.test(html)&&/HIST_GROUP_STATE\[id\]=nextOpen/.test(html)&&/open=historyGroupOpen\(weekId/.test(html),'L etat replie de l historique n est pas conserve pendant les rafraichissements.');
check(/id="hist-search"/.test(html)&&/function filterHistoryRows\(value\)/.test(html)&&/data-hsearch=/.test(html),'Le filtre de recherche de l historique est absent.');
check(/function isReportPrintingAllowed\(\)/.test(html)&&/function disableIframePrintButtons\(html\)/.test(html)&&/printAllowed&&html\.includes\('@page'\)/.test(html),'L impression des rapports n est pas limitee aux ordinateurs.');

check(/function getCaserneAdmin\(caserneId\)/.test(html)&&/function setCaserneAdmin\(caserneId,login\)/.test(html)&&/adminLogin:d\.adminLogin\|\|''/.test(html),'La designation unique de l administrateur de caserne est absente.');
check(/function repairKnownChefCorpsAssignment\(\)/.test(html)&&/account\.prenom='Vincent';account\.nom='Fabre'/.test(html)&&/desiredLogin='fabre\.vincent'/.test(html),'La restauration de Vincent Fabre comme chef de corps est absente.');
check(/function getChefCorpsCandidates\(\)/.test(html)&&/function setChefCorpsAccount\(login\)/.test(html)&&/onchange="setChefCorpsAccount\(this\.value\)"/.test(html),'La designation du chef de corps par le superadmin est absente.');
check(/Chef de Corps · '\+\(c\?c\.nom:'État-Major'\)/.test(html),'Le libelle visible Etat-Major du chef de corps est absent.');
check(/const etatMajorHtml=/.test(html)&&/onclick="saAccederEtatMajor\(\)"/.test(html)&&/function saRetourEtatMajor\(\)/.test(html),'La carte Etat-Major ou son acces depuis le superadmin est absent.');
check(/id="email-EMAJ"/.test(html)&&/onclick="saSaveEmail\('EMAJ'\)"/.test(html),'Le champ e-mail generique de l Etat-Major est absent.');
check(/function isInterventionComptabilisee\(iv\)/.test(html)&&/iv\.s==='terminee'&&!iv\._refugeAnimalier/.test(html),'La regle d exclusion des interventions annulees ou transferees au refuge est absente.');
check(/filter\(isInterventionComptabilisee\)/.test(html)&&/isInterventionComptabilisee\(iv\)&&adminExportInterventionStartDate/.test(html),'Les statistiques ou l export ne reutilisent pas la regle des interventions comptabilisees.');
check(/const ti=IVS\.filter\(iv=>!iv\._isPilip&&\['en-attente','selectionne','en-cours'\]\.includes\(iv\.s\)\)/.test(html),'Les compteurs des statuts actifs sont encore limites a la date du jour.');
check(/function statsCommunesIntervenuesEnPremier\(interventions\)/.test(html)&&/activeB-activeA\|\|String\(a\)\.localeCompare/.test(html),'Le tri des communes avec interventions en premier est absent.');
check((html.match(/statsCommunesIntervenuesEnPremier\(ivs\)/g)||[]).length>=4,'Le tri prioritaire des communes n est pas applique a toutes les vues statistiques.');
check(/function statsAppelsEnregistres\(interventions\)/.test(html)&&/function rStatsAppels\(\)/.test(html),'Le compteur historique des appels par utilisateur est absent.');
check(/\['appels','Appels'\]/.test(html)&&/stVue==='appels'/.test(html)&&/Total annuel/.test(html),'La vue administrateur des appels n est pas accessible depuis les statistiques.');
check(/monthTotals/.test(html)&&/monthHeaders/.test(html)&&/ST_MOIS\.map/.test(html)&&/totalYear/.test(html),'Les douze mois et le total annuel des appels sont incomplets.');
check(/findHistoricalAccountByLogin\(login\)/.test(html)&&/historicalName/.test(html),'Les anciens identifiants des opérateurs ne sont pas résolus vers leur nom complet.');
check(/function _rcRowWritableHere\(row\)/.test(html)&&/filter\(_rcRowWritableHere\)/.test(html),'La file de synchronisation n est pas limitée à la caserne active.');
check(/function _rcPrunePendingDirty\(candidateRows\)/.test(html)&&/_rcPrunePendingDirty\(candidate\)/.test(html),'Les éléments de synchronisation devenus impossibles à envoyer ne sont pas nettoyés.');
check(/_jbSetStatus\('error'\)/.test(html)&&/en attente/.test(html),'Les erreurs de synchronisation ne sont pas distinguées des actions simplement en attente.');
check(/key==='cond'.*return 'conducteur'/.test(html)&&/user\.l===currentLogin\?' selected'/.test(html),'Le conducteur abrégé déjà affecté n est pas présélectionné dans le compte rendu.');
check(/function interventionNumberingDateKey\(reference,annee\)/.test(html)&&/adminExportInterventionStartDate\(reference\)/.test(html),'La numérotation ne repose pas sur la date réelle de début d intervention.');
check(/function agaiRepairMonthlyNumberingConflicts\(\)/.test(html)&&/Numérotation mensuelle corrigée/.test(html),'La correction automatique des doublons mensuels est absente.');
check(/La politique Supabase réserve _GLOBAL au superadmin/.test(html)&&/return !!\(CURRENT_CASERNE_ID&&row\.caserne===CURRENT_CASERNE_ID\)/.test(html),'La ligne globale peut encore bloquer la synchronisation des utilisateurs de caserne.');
check(/candidate\.filter\(function\(r\)\{ return _rcPendingDirty\.has\(r\.id\); \}\)/.test(html),'Une prise d appel en attente n est pas envoyée isolément.');
check(/let _rcLastSyncError = ''/.test(html)&&/await resp\.text\(\)/.test(html)&&/Synchronisation :/.test(html),'Le détail des erreurs de synchronisation n est pas conservé pour le diagnostic.');
check(/function _rcUniqueRowsById\(rows\)/.test(html)&&(html.match(/_rcUniqueRowsById\(/g)||[]).length>=3,'Les doublons locaux ne sont pas éliminés avant l envoi à Supabase.');
check(/function makeInterventionRecordId\(displayNum\)/.test(html),'Les interventions ne disposent pas d un identifiant technique unique.');
check(/function _rcRepairDuplicateLocalRecordIds\(\)/.test(html)&&(html.match(/_rcRepairDuplicateLocalRecordIds\(/g)||[]).length>=3,'Les anciens doublons d interventions ne sont pas réparés avant synchronisation.');
check(/if\(!selC2\|\|!addr\|\|addr\.length<4\|\|!nat\)/.test(html)&&/nm\(x\.com\)===nc/.test(html),'Le bandeau des interventions précédentes peut apparaître sans commune ou pour une autre commune.');
check(/class="astr-fct-col" title="Fonction"[\s\S]{0,180}>Fct<\/th>/.test(html)&&/--astr-slot-width:\$\{gran>=60\?30:18\}px/.test(html),'La colonne Fct du planning n est pas compactée au profit des créneaux.');
check(/#astr-planning-grid table\{font-size:10px;width:100%!important;min-width:100%!important;table-layout:fixed;\}/.test(html)&&/#astr-planning-grid \.astr-slot-col\{width:auto!important;min-width:0!important;max-width:none!important;/.test(html),'Les 24 créneaux du planning mobile ne tiennent pas dans la largeur disponible.');
check(/th\[style\*="min-width:130px"\]\{width:112px!important;min-width:112px!important;max-width:112px!important;/.test(html),'La colonne des agents du planning mobile reste trop étroite.');
check(/const nbJour=ivStats\.filter\(iv=>statsInterventionInPeriod\(iv,jourStr\)\)\.length\+pilpStats\.filter/.test(html)&&/Interventions aujourd'hui/.test(html),'La carte des interventions du jour est absente de l accueil.');
check(!/Appels enregistrés \(session\)/.test(html),'L ancien compteur des appels de la session est encore affiche sur l accueil.');
check(/caserneId==='CIS05'[\s\S]{0,160}pascaldouvrin/.test(html)&&/right==='Administration'&&!isSuperAdmin\(\)/.test(html),'Pascal Douvrin ou la protection du droit Administration est absent.');
check(/async function _rcProtectSensitiveGlobalRow\(rows\)/.test(html)&&/protectedKeys=\['GLOBAL_ACCOUNTS'/.test(html)&&/rows=await _rcProtectSensitiveGlobalRow\(rows\)/.test(html),'Les comptes privilegies ne sont pas proteges pendant la synchronisation.');
check(/if\(ccBtn\)ccBtn\.style\.display='none'/.test(html)&&/Le compte du chef de corps est g\\u00e9r\\u00e9 uniquement par le super-administrateur/.test(html),'Le compte du chef de corps peut encore etre modifie hors superadmin.');

check(/const mobileGrid=window\.matchMedia&&window\.matchMedia\('\(max-width:1024px\)'\)\.matches;/.test(html)&&/const agentW=mobileGrid\?118:160;/.test(html)&&/const colW=mobileGrid\?48:36;/.test(html),'L astreinte telephonique reste illisible sur un smartphone en paysage.');

check(/function isAstreinteTelephoneDesktopAllowed\(\)/.test(html)&&/btnTel\.style\.display=isChefOuAdjoint\(\)&&isAstreinteTelephoneDesktopAllowed\(\)\?'':'none'/.test(html)&&/if\(sub==='tel'&&!isAstreinteTelephoneDesktopAllowed\(\)\)/.test(html),'L astreinte telephonique reste accessible sur smartphone ou tablette.');

if(failures.length){
  console.error('ÉCHEC ('+failures.length+')');
  failures.forEach(f=>console.error('- '+f));
  process.exit(1);
}

console.log('OK — syntaxe, secrets, mots de passe, e-mail, sauvegarde et règles Supabase vérifiés.');
